# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
   name: az400m05l05a-pool
 demands:
 - agent.name -equals DESKTOP-MN5GRV4

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) 
  displayName: 'dotnet publish $(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
   rootFolderOrFile: 'FunctionAppHttptrigger/bin/Release/net6.0/publish'
   includeRootFolder: false
   archiveType: zip
   archiveFile: '$(Build.ArtifactStagingDirectory)/FunctionAppHttptrigger/$(Build.BuildId).zip'
   replaceExistingArchive: true 
  displayName: 'Function zip files'  

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/FunctionAppHttptrigger'
    artifactName: 'Publish'
  displayName: 'Function publish to pipeline'
